Repository miniRT-however-we-are-largeRT/miniRT, pull requests merged in 2025-01, with the labels that each got.

#6 Docs: Commit Convention 작성 (#2)
  README.md
Labels: 📃 Docs

#7 fix: Object 파싱 수정 (#3)
  inc/error_handle.h
  scenes/mandatory.rt
  src/main.c
  src/parse/parse.c
  src/parse/parse_file.c
  src/parse/parse_object.c
Labels: 🐞 BugFix

#12 Refact: 메모리 누수 막기
  inc/minirt.h
  src/main.c
  src/parse/parse.c
  src/parse/parse_file.c
  src/parse/parse_object.c
  src/parse/parse_utils.c
  src/rt/window.c
  src/utils/error.c
  src/utils/object.c
  src/utils/utils.c
Labels: 🔨 Refactor

#14 Refact: 그림자 버그 수정
  Makefile
  inc/light.h
  inc/minirt.h
  inc/scene.h
  inc/struct_set.h
  lib/ft_atof.c
  scenes/mandatory.rt
  scenes/test.rt
  src/main.c
  src/parse/parse_init.c
  src/parse/parse_object.c
  src/parse/parse_utils.c
  src/rt/canvas.c
  src/rt/hit.c
  src/rt/light.c
  src/rt/run.c
  src/rt/scene.c
  src/utils/object.c
Labels: 🔨 Refactor

#15 Refact/norm #9
  inc/parse.h
  src/main.c
  src/parse/parse.c
  src/parse/parse_file.c
  src/parse/parse_init.c
  src/parse/parse_object.c
  src/rt/object_init.c
  src/rt/object_render.c
  src/rt/run.c
  src/rt/window.c
  src/utils/object.c
Labels: 🔨 Refactor

#17 Refact/camera #9
  inc/struct_set.h
  scenes/h.rt
  scenes/mandatory.rt
  scenes/test.rt
  src/main.c
  src/parse/parse_init.c
  src/parse/parse_object.c
  src/rt/canvas.c
  src/rt/hit.c
  src/rt/light.c
  src/rt/ray.c
  src/rt/run.c
Labels: ✨ Feature

#18 refact: float -> double (#9)
  inc/anti_alias.h
  inc/light.h
  inc/minirt.h
  inc/move.h
  inc/parse.h
  inc/ray.h
  inc/scene.h
  inc/struct_set.h
  inc/structure.h
  inc/utils.h
  inc/vec.h
  lib/ft_atof.c
  lib/libft.h
  scenes/h.rt
  scenes/scene1.rt
  scenes/scene2.rt
  scenes/scene3.rt
  scenes/scene4.rt
  scenes/scene5.rt
  scenes/scene6.rt
  scenes/scene7.rt
  scenes/scene8.rt
  src/parse/parse_init.c
  src/parse/parse_object.c
  src/parse/parse_utils.c
  src/rt/anti_alias.c
  src/rt/canvas.c
  src/rt/hit.c
  src/rt/ray.c
  src/rt/run.c
  src/rt/scene.c
  src/rt/vec1.c
  src/rt/vec2.c
  src/rt/vec3.c
  src/rt/window.c
  src/utils/object.c
  src/utils/utils.c
Labels: 🔨 Refactor

#19 Refact/elements #16
  .gitignore
  Makefile
  inc/anti_alias.h
  inc/bool.h
  inc/error_handle.h
  inc/light.h
  inc/main.h
  inc/minirt.h
  inc/move.h
  inc/parse.h
  inc/ray.h
  inc/scene.h
  inc/struct_set.h
  inc/structure.h
  inc/utils.h
  inc/vec.h
  lib/ft_atof.c
  lib/mlx/Makefile
  lib/mlx/font.c
  lib/mlx/interface.swift
  lib/mlx/man/man3/mlx.3
  lib/mlx/man/man3/mlx_loop.3
  lib/mlx/man/man3/mlx_new_image.3
  lib/mlx/man/man3/mlx_new_window.3
  lib/mlx/man/man3/mlx_pixel_put.3
  lib/mlx/mlx.h
  lib/mlx/mlx_image.swift
  lib/mlx/mlx_image.swiftsourceinfo
  lib/mlx/mlx_init.swift
  lib/mlx/mlx_init.swiftsourceinfo
  lib/mlx/mlx_png.c
  lib/mlx/mlx_rgb.c
  lib/mlx/mlx_string_put.c
  lib/mlx/mlx_window.swift
  lib/mlx/mlx_window.swiftsourceinfo
  lib/mlx/mlx_xpm.c
  scenes/cyl.rt
  scenes/scene1.rt
  scenes/sphere.rt
  src/main.c
  src/parse/parse_file.c
  src/parse/parse_init.c
  src/rt/anti_alias.c
  src/rt/camera.c
  src/rt/canvas.c
  src/rt/hit.c
  src/rt/hit_cylinder.c
  src/rt/light.c
  src/rt/move.c
  src/rt/ray.c
  src/rt/run.c
  src/rt/scene.c
  src/rt/vec3.c
Labels: ✨ Feature

#21 Refact/norm #20
  Makefile
  inc/minirt.h
  inc/struct_set.h
  lib/ft_atof.c
  lib/ft_split_utils.c
  lib/mlx/mlx_image.swiftsourceinfo
  lib/mlx/mlx_init.swiftsourceinfo
  lib/mlx/mlx_window.swiftsourceinfo
  src/main.c
  src/rt/window.c
Labels: 🔨 Refactor

#22 refact:unnecessary elements deleted (#20)
  inc/bool.h
  inc/light.h
  inc/minirt.h
  inc/scene.h
  inc/struct_set.h
  lib/mlx/mlx_image.swiftsourceinfo
  lib/mlx/mlx_init.swiftsourceinfo
  lib/mlx/mlx_window.swiftsourceinfo
  src/main.c
  src/parse/parse_init.c
  src/rt/light.c
  src/rt/run.c
Labels: 🔨 Refactor

#24 hotfix: parse memory leaks fixed(#11)
  src/parse/parse_file.c
Labels: 🐞 BugFix

#26 Feature/bonus #25
  .gitignore
  Makefile
  inc/minirt.h
  inc/parse.h
  inc/ray.h
  inc/struct_set.h
  inc/vec.h
  lib/mlx/mlx_image.swiftsourceinfo
  lib/mlx/mlx_init.swiftsourceinfo
  lib/mlx/mlx_window.swiftsourceinfo
  scenes/camera.rt
  scenes/scene2.rt
  scenes/scene4.rt
  scenes/test.rt
  src/main.c
  src/parse/parse.c
  src/parse/parse_file.c
  src/parse/parse_object.c
  src/rt/camera.c
  src/rt/hit.c
  src/rt/hit_cone.c
  src/rt/hit_cylinder.c
Labels: ✨ Feature, 🔨 Refactor
